### ISSUE TITLE
Config page is not showing up on Extensions menu

### ISSUE THREAD

**Issue by martacsilva** [Ferrisx4/gene_jbrowse_field#7]
Hi,
I have installed and enabled the module, and I have cleared the cache. But when I go to the Extensions menu, I don't have an option to reach the configuration of this module. 
Anything else I can do?

Thanks in advance, 
Marta

**Comment by Ferrisx4** [comment]
Hi Marta
I'm not sure why it would not be showing up. If you manually navigate to the config page by browsing to yourtripalsite.com/admin/tripal/extension/gene_jbrowse_field/config , does anything show up for you?

My guess would be that it is a Permissions issue.

**Comment by martacsilva** [comment]
Hi,
It wasn't showing up even if I manually navigated to the page, I also checked the permissions.
We have since solved it with something else, and I forgot to close this issue, sorry. Hope it was something to do with my installation and not with the module.

Thank you!
